//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseDragonCafe.Main.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> PortionSize { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
